import fs from 'node:fs';
import assert from 'node:assert/strict';
const main = fs.readFileSync(new URL('../electron/main.cjs', import.meta.url), 'utf8');
const renderer = fs.readFileSync(new URL('../src/main.tsx', import.meta.url), 'utf8');
const pkg = JSON.parse(fs.readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const prep = fs.readFileSync(new URL('./prepare-tor.mjs', import.meta.url), 'utf8');
const installer = fs.readFileSync(new URL('../INSTALL_WINDOWS.bat', import.meta.url), 'utf8');
assert.equal(pkg.version, '3.4.1');
assert.equal(pkg.scripts['prepare:tor'], 'node scripts/prepare-tor.mjs');
assert(Array.isArray(pkg.build.extraResources) && pkg.build.extraResources.some((x) => x.to === 'tor-bundle'));
assert(pkg.build.files.includes('build/icon.ico'));
assert.equal(pkg.build.win.icon, 'build/icon.ico');
assert.equal(pkg.build.nsis.installerIcon, 'build/icon.ico');
assert(main.includes("const { spawn } = require('node:child_process');"));
assert(main.includes('startIntegratedTor'));
assert(main.includes("source: 'integrated'"));
assert(main.includes('bundledTorExecutable'));
assert(main.includes('Integrated Tor bootstrapping'));
assert(main.includes("proxyRules: 'socks5://127.0.0.1:1'"), 'Tor must remain fail closed while connecting');
assert(main.includes('stopManagedTor'));
assert(main.includes("mainWindow.setIcon"));
assert(renderer.includes('INTEGRATED TOR'));
assert(renderer.includes('Integrated Tor ready on demand'));
assert(prep.includes('15.0.19'));
assert(prep.includes('6ac067402c7b4a3dc37887ed3754b3914b67fdc220c966190683e9ccf91abf0f'));
assert(installer.includes('npm run prepare:tor'));
console.log('v3.3 integrated-Tor/icon/single-installer regression tests passed.');
