import fs from 'node:fs';
import assert from 'node:assert/strict';
const main = fs.readFileSync(new URL('../electron/main.cjs', import.meta.url), 'utf8');
const preload = fs.readFileSync(new URL('../electron/preload.cjs', import.meta.url), 'utf8');
const renderer = fs.readFileSync(new URL('../src/main.tsx', import.meta.url), 'utf8');
const styles = fs.readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');
const pkg = JSON.parse(fs.readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
assert.equal(pkg.version, '3.4.1');
assert(renderer.includes('COMMON NETWORK MIND MAP'));
assert(renderer.includes('ALL RELATIONSHIPS'));
assert(renderer.includes('COMMON FOLLOWERS'));
assert(renderer.includes('COMMON FOLLOWING'));
assert(renderer.includes('VISIBLE IDENTITIES'));
assert(renderer.includes('onDoubleClick'));
assert(styles.includes('.mind-map-wrap'));
assert(styles.includes('.graph-inspector'));
assert(main.includes('runBackgroundTask'));
assert(main.includes("Background task failed:"));
assert(main.includes("runBackgroundTask('Automatic sweep'"));
assert(main.includes("runBackgroundTask('Incremental archive cycle'"));
assert(main.includes('Network page collector recovered from a renderer error'));
assert(main.includes('collector.lastError'));
assert(preload.includes('onBackgroundError:'));
assert(renderer.includes('onBackgroundError'));
console.log('v3.2 mind-map/background-error regression tests passed.');
